// Code generated by tygo. DO NOT EDIT.

//////////
// source: health.go

/**
 * HealthResponse is the JSON shape for monolith-stream-api health checks.
 * Tygo emits apps/monolith-stream/src/types/backend.d.ts from this package.
 */
export interface HealthResponse {
  ok: boolean;
}
