// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO auth_credentials (user_id, credential_id, public_key, sign_count, aaguid, backup_eligible, backup_state, credential_flags_initialized, credential_label)
VALUES ($1, $2, $3, $4, $5, $6, $7, TRUE, $8)
RETURNING id, user_id, credential_id, public_key, sign_count, aaguid, backup_eligible, backup_state, credential_flags_initialized, created_at, revoked_at, last_used_at, credential_label
`

type CreateCredentialParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	CredentialID    []byte      `json:"credential_id"`
	PublicKey       []byte      `json:"public_key"`
	SignCount       pgtype.Int8 `json:"sign_count"`
	Aaguid          []byte      `json:"aaguid"`
	BackupEligible  bool        `json:"backup_eligible"`
	BackupState     bool        `json:"backup_state"`
	CredentialLabel pgtype.Text `json:"credential_label"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Aaguid,
		arg.BackupEligible,
		arg.BackupState,
		arg.CredentialLabel,
	)
	var i AuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Aaguid,
		&i.BackupEligible,
		&i.BackupState,
		&i.CredentialFlagsInitialized,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CredentialLabel,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth_users (email) 
VALUES ($1) 
RETURNING id, email, created_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i AuthUser
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getActiveCredentialsByUserID = `-- name: GetActiveCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, aaguid, backup_eligible, backup_state, credential_flags_initialized, created_at, revoked_at, last_used_at, credential_label
FROM auth_credentials
WHERE user_id = $1 
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthCredential, error) {
	rows, err := q.db.Query(ctx, getActiveCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthCredential
	for rows.Next() {
		var i AuthCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Aaguid,
			&i.BackupEligible,
			&i.BackupState,
			&i.CredentialFlagsInitialized,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CredentialLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialByCredentialID = `-- name: GetCredentialByCredentialID :one
SELECT id, user_id, credential_id, public_key, sign_count, aaguid, backup_eligible, backup_state, credential_flags_initialized, created_at, revoked_at, last_used_at, credential_label
FROM auth_credentials
WHERE credential_id = $1
LIMIT 1
`

func (q *Queries) GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByCredentialID, credentialID)
	var i AuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Aaguid,
		&i.BackupEligible,
		&i.BackupState,
		&i.CredentialFlagsInitialized,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CredentialLabel,
	)
	return i, err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, aaguid, backup_eligible, backup_state, credential_flags_initialized, created_at, revoked_at, last_used_at, credential_label
FROM auth_credentials 
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthCredential, error) {
	rows, err := q.db.Query(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthCredential
	for rows.Next() {
		var i AuthCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Aaguid,
			&i.BackupEligible,
			&i.BackupState,
			&i.CredentialFlagsInitialized,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CredentialLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email 
FROM auth_users 
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at
FROM auth_users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const revokeCredential = `-- name: RevokeCredential :exec
UPDATE auth_credentials
SET revoked_at = NOW()
WHERE id = $1 
  AND user_id = $2
`

type RevokeCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error {
	_, err := q.db.Exec(ctx, revokeCredential, arg.ID, arg.UserID)
	return err
}

const touchCredentialLastUsed = `-- name: TouchCredentialLastUsed :exec
UPDATE auth_credentials
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchCredentialLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCredentialLastUsed, id)
	return err
}

const updateCredentialFlags = `-- name: UpdateCredentialFlags :exec
UPDATE auth_credentials
SET backup_eligible = $1,
    backup_state = $2,
    credential_flags_initialized = TRUE
WHERE credential_id = $3
`

type UpdateCredentialFlagsParams struct {
	BackupEligible bool   `json:"backup_eligible"`
	BackupState    bool   `json:"backup_state"`
	CredentialID   []byte `json:"credential_id"`
}

func (q *Queries) UpdateCredentialFlags(ctx context.Context, arg UpdateCredentialFlagsParams) error {
	_, err := q.db.Exec(ctx, updateCredentialFlags, arg.BackupEligible, arg.BackupState, arg.CredentialID)
	return err
}

const updateCredentialLabel = `-- name: UpdateCredentialLabel :exec
UPDATE auth_credentials
SET credential_label = $3
WHERE id = $1
  AND user_id = $2
`

type UpdateCredentialLabelParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	CredentialLabel pgtype.Text `json:"credential_label"`
}

func (q *Queries) UpdateCredentialLabel(ctx context.Context, arg UpdateCredentialLabelParams) error {
	_, err := q.db.Exec(ctx, updateCredentialLabel, arg.ID, arg.UserID, arg.CredentialLabel)
	return err
}

const updateCredentialSignCount = `-- name: UpdateCredentialSignCount :exec
UPDATE auth_credentials 
SET sign_count = $1, last_used_at = NOW() 
WHERE credential_id = $2
`

type UpdateCredentialSignCountParams struct {
	SignCount    pgtype.Int8 `json:"sign_count"`
	CredentialID []byte      `json:"credential_id"`
}

func (q *Queries) UpdateCredentialSignCount(ctx context.Context, arg UpdateCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateCredentialSignCount, arg.SignCount, arg.CredentialID)
	return err
}
