// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertFiszkiQuestions implements pgx.CopyFromSource.
type iteratorForInsertFiszkiQuestions struct {
	rows                 []InsertFiszkiQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertFiszkiQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertFiszkiQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StudySetID,
		r.rows[0].Position,
		r.rows[0].QuestionType,
		r.rows[0].Prompt,
		r.rows[0].Answer,
		r.rows[0].Choices,
		r.rows[0].CorrectIndices,
	}, nil
}

func (r iteratorForInsertFiszkiQuestions) Err() error {
	return nil
}

func (q *Queries) InsertFiszkiQuestions(ctx context.Context, arg []InsertFiszkiQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"fiszki_question"}, []string{"study_set_id", "position", "question_type", "prompt", "answer", "choices", "correct_indices"}, &iteratorForInsertFiszkiQuestions{rows: arg})
}

// iteratorForInsertFiszkiSessionAnswers implements pgx.CopyFromSource.
type iteratorForInsertFiszkiSessionAnswers struct {
	rows                 []InsertFiszkiSessionAnswersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertFiszkiSessionAnswers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertFiszkiSessionAnswers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SessionID,
		r.rows[0].QuestionID,
		r.rows[0].QuestionNumber,
		r.rows[0].SelectedIndices,
		r.rows[0].FlashcardResult,
		r.rows[0].IsCorrect,
		r.rows[0].ResponseTimeMs,
	}, nil
}

func (r iteratorForInsertFiszkiSessionAnswers) Err() error {
	return nil
}

func (q *Queries) InsertFiszkiSessionAnswers(ctx context.Context, arg []InsertFiszkiSessionAnswersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"fiszki_session_answer"}, []string{"session_id", "question_id", "question_number", "selected_indices", "flashcard_result", "is_correct", "response_time_ms"}, &iteratorForInsertFiszkiSessionAnswers{rows: arg})
}
