// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deviceKeyOwnedByUser = `-- name: DeviceKeyOwnedByUser :one
SELECT EXISTS(
  SELECT 1 FROM auth_public_key WHERE id = $1 AND user_id = $2
) AS ok
`

type DeviceKeyOwnedByUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeviceKeyOwnedByUser(ctx context.Context, arg DeviceKeyOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, deviceKeyOwnedByUser, arg.ID, arg.UserID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const fetchPublicKeysByUserID = `-- name: FetchPublicKeysByUserID :many
SELECT id AS device_key_id, public_key 
FROM auth_public_key 
WHERE user_id = $1
`

type FetchPublicKeysByUserIDRow struct {
	DeviceKeyID pgtype.UUID `json:"device_key_id"`
	PublicKey   []byte      `json:"public_key"`
}

func (q *Queries) FetchPublicKeysByUserID(ctx context.Context, userID pgtype.UUID) ([]FetchPublicKeysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, fetchPublicKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPublicKeysByUserIDRow
	for rows.Next() {
		var i FetchPublicKeysByUserIDRow
		if err := rows.Scan(&i.DeviceKeyID, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO auth_public_key (user_id, public_key) 
VALUES ($1, $2) 
RETURNING id
`

type RegisterDeviceParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	PublicKey []byte      `json:"public_key"`
}

func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, registerDevice, arg.UserID, arg.PublicKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeDevice = `-- name: RevokeDevice :exec
DELETE FROM auth_public_key 
WHERE id = $1 AND user_id = $2
`

type RevokeDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice, arg.ID, arg.UserID)
	return err
}
