// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drop_sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeDropSessionForHost = `-- name: CloseDropSessionForHost :one
UPDATE monolith_drop_session
SET closed_at = NOW()
WHERE id = $1
  AND host_user_id = $2
  AND closed_at IS NULL
RETURNING id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
`

type CloseDropSessionForHostParams struct {
	ID         pgtype.UUID `json:"id"`
	HostUserID pgtype.UUID `json:"host_user_id"`
}

func (q *Queries) CloseDropSessionForHost(ctx context.Context, arg CloseDropSessionForHostParams) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, closeDropSessionForHost, arg.ID, arg.HostUserID)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDropSession = `-- name: CreateDropSession :one
INSERT INTO monolith_drop_session (host_user_id, peer_host, join_secret, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
`

type CreateDropSessionParams struct {
	HostUserID pgtype.UUID        `json:"host_user_id"`
	PeerHost   string             `json:"peer_host"`
	JoinSecret string             `json:"join_secret"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDropSession(ctx context.Context, arg CreateDropSessionParams) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, createDropSession,
		arg.HostUserID,
		arg.PeerHost,
		arg.JoinSecret,
		arg.ExpiresAt,
	)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDropSessionByJoinSecret = `-- name: GetDropSessionByJoinSecret :one
SELECT id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
FROM monolith_drop_session
WHERE join_secret = $1
  AND expires_at > NOW()
`

func (q *Queries) GetDropSessionByJoinSecret(ctx context.Context, joinSecret string) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, getDropSessionByJoinSecret, joinSecret)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDropSessionByJoinSecretRaw = `-- name: GetDropSessionByJoinSecretRaw :one
SELECT id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
FROM monolith_drop_session
WHERE join_secret = $1
`

func (q *Queries) GetDropSessionByJoinSecretRaw(ctx context.Context, joinSecret string) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, getDropSessionByJoinSecretRaw, joinSecret)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDropSessionForHost = `-- name: GetDropSessionForHost :one
SELECT id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
FROM monolith_drop_session
WHERE id = $1
  AND host_user_id = $2
  AND expires_at > NOW()
`

type GetDropSessionForHostParams struct {
	ID         pgtype.UUID `json:"id"`
	HostUserID pgtype.UUID `json:"host_user_id"`
}

func (q *Queries) GetDropSessionForHost(ctx context.Context, arg GetDropSessionForHostParams) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, getDropSessionForHost, arg.ID, arg.HostUserID)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDropSessionForParticipant = `-- name: GetDropSessionForParticipant :one
SELECT id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
FROM monolith_drop_session
WHERE id = $1
  AND (host_user_id = $2 OR guest_user_id = $2)
  AND expires_at > NOW()
`

type GetDropSessionForParticipantParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDropSessionForParticipant(ctx context.Context, arg GetDropSessionForParticipantParams) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, getDropSessionForParticipant, arg.SessionID, arg.UserID)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const joinDropSession = `-- name: JoinDropSession :one
UPDATE monolith_drop_session
SET peer_guest = $2,
    guest_user_id = $3
WHERE join_secret = $1
  AND peer_guest IS NULL
  AND expires_at > NOW()
RETURNING id, host_user_id, guest_user_id, peer_host, peer_guest, join_secret, expires_at, closed_at, created_at
`

type JoinDropSessionParams struct {
	JoinSecret  string      `json:"join_secret"`
	PeerGuest   pgtype.Text `json:"peer_guest"`
	GuestUserID pgtype.UUID `json:"guest_user_id"`
}

func (q *Queries) JoinDropSession(ctx context.Context, arg JoinDropSessionParams) (MonolithDropSession, error) {
	row := q.db.QueryRow(ctx, joinDropSession, arg.JoinSecret, arg.PeerGuest, arg.GuestUserID)
	var i MonolithDropSession
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GuestUserID,
		&i.PeerHost,
		&i.PeerGuest,
		&i.JoinSecret,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}
