// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fiszki.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFiszkiStudySetsByUser = `-- name: CountFiszkiStudySetsByUser :one
SELECT COUNT(*)
FROM fiszki_study_set
WHERE user_id = $1
`

func (q *Queries) CountFiszkiStudySetsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFiszkiStudySetsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFiszkiSession = `-- name: CreateFiszkiSession :one
INSERT INTO fiszki_session (user_id, study_set_id, mode, total_questions, correct_answers, score,
                            time_spent_seconds, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ended_at
`

type CreateFiszkiSessionParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	StudySetID       pgtype.UUID        `json:"study_set_id"`
	Mode             string             `json:"mode"`
	TotalQuestions   int32              `json:"total_questions"`
	CorrectAnswers   int32              `json:"correct_answers"`
	Score            int32              `json:"score"`
	TimeSpentSeconds int32              `json:"time_spent_seconds"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
}

type CreateFiszkiSessionRow struct {
	ID      pgtype.UUID        `json:"id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateFiszkiSession(ctx context.Context, arg CreateFiszkiSessionParams) (CreateFiszkiSessionRow, error) {
	row := q.db.QueryRow(ctx, createFiszkiSession,
		arg.UserID,
		arg.StudySetID,
		arg.Mode,
		arg.TotalQuestions,
		arg.CorrectAnswers,
		arg.Score,
		arg.TimeSpentSeconds,
		arg.StartedAt,
	)
	var i CreateFiszkiSessionRow
	err := row.Scan(&i.ID, &i.EndedAt)
	return i, err
}

const createFiszkiStudySet = `-- name: CreateFiszkiStudySet :one
INSERT INTO fiszki_study_set (user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateFiszkiStudySetParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateFiszkiStudySet(ctx context.Context, arg CreateFiszkiStudySetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createFiszkiStudySet, arg.UserID, arg.Name, arg.Description)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteFiszkiCardProgressForSet = `-- name: DeleteFiszkiCardProgressForSet :execrows
DELETE
FROM fiszki_card_progress cp
    USING fiszki_question q
WHERE cp.question_id = q.id
  AND cp.user_id = $1
  AND q.study_set_id = $2
`

type DeleteFiszkiCardProgressForSetParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	StudySetID pgtype.UUID `json:"study_set_id"`
}

func (q *Queries) DeleteFiszkiCardProgressForSet(ctx context.Context, arg DeleteFiszkiCardProgressForSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFiszkiCardProgressForSet, arg.UserID, arg.StudySetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFiszkiStudySet = `-- name: DeleteFiszkiStudySet :execrows
DELETE
FROM fiszki_study_set
WHERE id = $1
  AND user_id = $2
`

type DeleteFiszkiStudySetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteFiszkiStudySet(ctx context.Context, arg DeleteFiszkiStudySetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFiszkiStudySet, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFiszkiOverallStats = `-- name: GetFiszkiOverallStats :one
SELECT COUNT(DISTINCT sess.study_set_id)::BIGINT          AS studied_set_count,
       COUNT(*)::BIGINT                                   AS session_count,
       COALESCE(AVG(sess.score), 0)::FLOAT                AS average_score,
       COALESCE(MAX(sess.score), 0)::BIGINT               AS best_score,
       COALESCE(SUM(sess.time_spent_seconds), 0)::BIGINT  AS total_time_spent_seconds,
       COALESCE(SUM(sess.total_questions), 0)::BIGINT     AS total_questions_answered,
       COALESCE(SUM(sess.correct_answers), 0)::BIGINT     AS total_correct_answers
FROM fiszki_session sess
WHERE sess.user_id = $1
`

type GetFiszkiOverallStatsRow struct {
	StudiedSetCount        int64   `json:"studied_set_count"`
	SessionCount           int64   `json:"session_count"`
	AverageScore           float64 `json:"average_score"`
	BestScore              int64   `json:"best_score"`
	TotalTimeSpentSeconds  int64   `json:"total_time_spent_seconds"`
	TotalQuestionsAnswered int64   `json:"total_questions_answered"`
	TotalCorrectAnswers    int64   `json:"total_correct_answers"`
}

func (q *Queries) GetFiszkiOverallStats(ctx context.Context, userID pgtype.UUID) (GetFiszkiOverallStatsRow, error) {
	row := q.db.QueryRow(ctx, getFiszkiOverallStats, userID)
	var i GetFiszkiOverallStatsRow
	err := row.Scan(
		&i.StudiedSetCount,
		&i.SessionCount,
		&i.AverageScore,
		&i.BestScore,
		&i.TotalTimeSpentSeconds,
		&i.TotalQuestionsAnswered,
		&i.TotalCorrectAnswers,
	)
	return i, err
}

const getFiszkiSession = `-- name: GetFiszkiSession :one
SELECT sess.id, sess.user_id, sess.study_set_id, sess.mode, sess.total_questions, sess.correct_answers, sess.score, sess.time_spent_seconds, sess.started_at, sess.ended_at, s.name AS study_set_name
FROM fiszki_session sess
         JOIN fiszki_study_set s ON s.id = sess.study_set_id
WHERE sess.id = $1
  AND sess.user_id = $2
`

type GetFiszkiSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetFiszkiSessionRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StudySetID       pgtype.UUID        `json:"study_set_id"`
	Mode             string             `json:"mode"`
	TotalQuestions   int32              `json:"total_questions"`
	CorrectAnswers   int32              `json:"correct_answers"`
	Score            int32              `json:"score"`
	TimeSpentSeconds int32              `json:"time_spent_seconds"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	StudySetName     string             `json:"study_set_name"`
}

func (q *Queries) GetFiszkiSession(ctx context.Context, arg GetFiszkiSessionParams) (GetFiszkiSessionRow, error) {
	row := q.db.QueryRow(ctx, getFiszkiSession, arg.ID, arg.UserID)
	var i GetFiszkiSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudySetID,
		&i.Mode,
		&i.TotalQuestions,
		&i.CorrectAnswers,
		&i.Score,
		&i.TimeSpentSeconds,
		&i.StartedAt,
		&i.EndedAt,
		&i.StudySetName,
	)
	return i, err
}

const getFiszkiStudySet = `-- name: GetFiszkiStudySet :one
SELECT id, user_id, name, description, created_at, updated_at
FROM fiszki_study_set
WHERE id = $1
  AND user_id = $2
`

type GetFiszkiStudySetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetFiszkiStudySet(ctx context.Context, arg GetFiszkiStudySetParams) (FiszkiStudySet, error) {
	row := q.db.QueryRow(ctx, getFiszkiStudySet, arg.ID, arg.UserID)
	var i FiszkiStudySet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertFiszkiQuestionsParams struct {
	StudySetID     pgtype.UUID `json:"study_set_id"`
	Position       int32       `json:"position"`
	QuestionType   string      `json:"question_type"`
	Prompt         string      `json:"prompt"`
	Answer         pgtype.Text `json:"answer"`
	Choices        []string    `json:"choices"`
	CorrectIndices []int32     `json:"correct_indices"`
	ImagePath      pgtype.Text `json:"image_path"`
}

type InsertFiszkiSessionAnswersParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	QuestionID      pgtype.UUID `json:"question_id"`
	QuestionNumber  int32       `json:"question_number"`
	SelectedIndices []int32     `json:"selected_indices"`
	FlashcardResult pgtype.Text `json:"flashcard_result"`
	IsCorrect       bool        `json:"is_correct"`
	ResponseTimeMs  int32       `json:"response_time_ms"`
}

const listFiszkiCardProgressBySet = `-- name: ListFiszkiCardProgressBySet :many
SELECT cp.user_id, cp.question_id, cp.status, cp.times_reviewed, cp.times_correct, cp.difficulty, cp.ease_factor, cp.interval_days, cp.consecutive_correct, cp.consecutive_incorrect, cp.last_reviewed_at, cp.next_review_at
FROM fiszki_card_progress cp
         JOIN fiszki_question q ON q.id = cp.question_id
WHERE cp.user_id = $1
  AND q.study_set_id = $2
`

type ListFiszkiCardProgressBySetParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	StudySetID pgtype.UUID `json:"study_set_id"`
}

func (q *Queries) ListFiszkiCardProgressBySet(ctx context.Context, arg ListFiszkiCardProgressBySetParams) ([]FiszkiCardProgress, error) {
	rows, err := q.db.Query(ctx, listFiszkiCardProgressBySet, arg.UserID, arg.StudySetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiszkiCardProgress
	for rows.Next() {
		var i FiszkiCardProgress
		if err := rows.Scan(
			&i.UserID,
			&i.QuestionID,
			&i.Status,
			&i.TimesReviewed,
			&i.TimesCorrect,
			&i.Difficulty,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.ConsecutiveCorrect,
			&i.ConsecutiveIncorrect,
			&i.LastReviewedAt,
			&i.NextReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiszkiQuestionsBySet = `-- name: ListFiszkiQuestionsBySet :many
SELECT id, study_set_id, position, question_type, prompt, answer, choices, correct_indices, created_at, image_path
FROM fiszki_question
WHERE study_set_id = $1
ORDER BY position
`

func (q *Queries) ListFiszkiQuestionsBySet(ctx context.Context, studySetID pgtype.UUID) ([]FiszkiQuestion, error) {
	rows, err := q.db.Query(ctx, listFiszkiQuestionsBySet, studySetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiszkiQuestion
	for rows.Next() {
		var i FiszkiQuestion
		if err := rows.Scan(
			&i.ID,
			&i.StudySetID,
			&i.Position,
			&i.QuestionType,
			&i.Prompt,
			&i.Answer,
			&i.Choices,
			&i.CorrectIndices,
			&i.CreatedAt,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiszkiSessionAnswers = `-- name: ListFiszkiSessionAnswers :many
SELECT a.question_number,
       a.selected_indices,
       a.flashcard_result,
       a.is_correct,
       a.response_time_ms,
       q.id AS question_id,
       q.question_type,
       q.prompt,
       q.answer,
       q.choices,
       q.correct_indices
FROM fiszki_session_answer a
         JOIN fiszki_question q ON q.id = a.question_id
WHERE a.session_id = $1
ORDER BY a.question_number
`

type ListFiszkiSessionAnswersRow struct {
	QuestionNumber  int32       `json:"question_number"`
	SelectedIndices []int32     `json:"selected_indices"`
	FlashcardResult pgtype.Text `json:"flashcard_result"`
	IsCorrect       bool        `json:"is_correct"`
	ResponseTimeMs  int32       `json:"response_time_ms"`
	QuestionID      pgtype.UUID `json:"question_id"`
	QuestionType    string      `json:"question_type"`
	Prompt          string      `json:"prompt"`
	Answer          pgtype.Text `json:"answer"`
	Choices         []string    `json:"choices"`
	CorrectIndices  []int32     `json:"correct_indices"`
}

func (q *Queries) ListFiszkiSessionAnswers(ctx context.Context, sessionID pgtype.UUID) ([]ListFiszkiSessionAnswersRow, error) {
	rows, err := q.db.Query(ctx, listFiszkiSessionAnswers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFiszkiSessionAnswersRow
	for rows.Next() {
		var i ListFiszkiSessionAnswersRow
		if err := rows.Scan(
			&i.QuestionNumber,
			&i.SelectedIndices,
			&i.FlashcardResult,
			&i.IsCorrect,
			&i.ResponseTimeMs,
			&i.QuestionID,
			&i.QuestionType,
			&i.Prompt,
			&i.Answer,
			&i.Choices,
			&i.CorrectIndices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiszkiStudySetsWithStats = `-- name: ListFiszkiStudySetsWithStats :many
SELECT s.id,
       s.name,
       s.description,
       s.created_at,
       s.updated_at,
       (SELECT COUNT(*)
        FROM fiszki_question q
        WHERE q.study_set_id = s.id)::BIGINT AS question_count,
       (SELECT COUNT(*)
        FROM fiszki_question q
        WHERE q.study_set_id = s.id
          AND q.question_type = 'flashcard')::BIGINT AS flashcard_count,
       (SELECT COUNT(*)
        FROM fiszki_card_progress cp
                 JOIN fiszki_question q ON q.id = cp.question_id
        WHERE cp.user_id = s.user_id
          AND q.study_set_id = s.id
          AND cp.status = 'known')::BIGINT AS known_count,
       (SELECT COUNT(*)
        FROM fiszki_card_progress cp
                 JOIN fiszki_question q ON q.id = cp.question_id
        WHERE cp.user_id = s.user_id
          AND q.study_set_id = s.id
          AND cp.status = 'unknown')::BIGINT AS unknown_count,
       (SELECT COUNT(*)
        FROM fiszki_session sess
        WHERE sess.study_set_id = s.id
          AND sess.user_id = s.user_id)::BIGINT AS session_count,
       (SELECT COALESCE(MAX(sess.score), 0)
        FROM fiszki_session sess
        WHERE sess.study_set_id = s.id
          AND sess.user_id = s.user_id)::BIGINT AS best_score,
       (SELECT COALESCE(AVG(sess.score), 0)
        FROM fiszki_session sess
        WHERE sess.study_set_id = s.id
          AND sess.user_id = s.user_id)::FLOAT AS average_score,
       (SELECT COALESCE(SUM(sess.time_spent_seconds), 0)
        FROM fiszki_session sess
        WHERE sess.study_set_id = s.id
          AND sess.user_id = s.user_id)::BIGINT AS total_time_spent_seconds,
       (SELECT MAX(sess.ended_at)
        FROM fiszki_session sess
        WHERE sess.study_set_id = s.id
          AND sess.user_id = s.user_id)::TIMESTAMPTZ AS last_attempt_at
FROM fiszki_study_set s
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

type ListFiszkiStudySetsWithStatsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	QuestionCount         int64              `json:"question_count"`
	FlashcardCount        int64              `json:"flashcard_count"`
	KnownCount            int64              `json:"known_count"`
	UnknownCount          int64              `json:"unknown_count"`
	SessionCount          int64              `json:"session_count"`
	BestScore             int64              `json:"best_score"`
	AverageScore          float64            `json:"average_score"`
	TotalTimeSpentSeconds int64              `json:"total_time_spent_seconds"`
	LastAttemptAt         pgtype.Timestamptz `json:"last_attempt_at"`
}

func (q *Queries) ListFiszkiStudySetsWithStats(ctx context.Context, userID pgtype.UUID) ([]ListFiszkiStudySetsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listFiszkiStudySetsWithStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFiszkiStudySetsWithStatsRow
	for rows.Next() {
		var i ListFiszkiStudySetsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionCount,
			&i.FlashcardCount,
			&i.KnownCount,
			&i.UnknownCount,
			&i.SessionCount,
			&i.BestScore,
			&i.AverageScore,
			&i.TotalTimeSpentSeconds,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFiszkiCardProgress = `-- name: UpsertFiszkiCardProgress :exec
INSERT INTO fiszki_card_progress (user_id, question_id, status, times_reviewed, times_correct, difficulty,
                                  ease_factor, interval_days, consecutive_correct, consecutive_incorrect,
                                  last_reviewed_at, next_review_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (user_id, question_id) DO UPDATE
    SET status                = EXCLUDED.status,
        times_reviewed        = EXCLUDED.times_reviewed,
        times_correct         = EXCLUDED.times_correct,
        difficulty            = EXCLUDED.difficulty,
        ease_factor           = EXCLUDED.ease_factor,
        interval_days         = EXCLUDED.interval_days,
        consecutive_correct   = EXCLUDED.consecutive_correct,
        consecutive_incorrect = EXCLUDED.consecutive_incorrect,
        last_reviewed_at      = EXCLUDED.last_reviewed_at,
        next_review_at        = EXCLUDED.next_review_at
`

type UpsertFiszkiCardProgressParams struct {
	UserID               pgtype.UUID        `json:"user_id"`
	QuestionID           pgtype.UUID        `json:"question_id"`
	Status               string             `json:"status"`
	TimesReviewed        int32              `json:"times_reviewed"`
	TimesCorrect         int32              `json:"times_correct"`
	Difficulty           float32            `json:"difficulty"`
	EaseFactor           float32            `json:"ease_factor"`
	IntervalDays         int32              `json:"interval_days"`
	ConsecutiveCorrect   int32              `json:"consecutive_correct"`
	ConsecutiveIncorrect int32              `json:"consecutive_incorrect"`
	LastReviewedAt       pgtype.Timestamptz `json:"last_reviewed_at"`
	NextReviewAt         pgtype.Timestamptz `json:"next_review_at"`
}

func (q *Queries) UpsertFiszkiCardProgress(ctx context.Context, arg UpsertFiszkiCardProgressParams) error {
	_, err := q.db.Exec(ctx, upsertFiszkiCardProgress,
		arg.UserID,
		arg.QuestionID,
		arg.Status,
		arg.TimesReviewed,
		arg.TimesCorrect,
		arg.Difficulty,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.ConsecutiveCorrect,
		arg.ConsecutiveIncorrect,
		arg.LastReviewedAt,
		arg.NextReviewAt,
	)
	return err
}
