// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCredential struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	CredentialID               []byte             `json:"credential_id"`
	PublicKey                  []byte             `json:"public_key"`
	SignCount                  pgtype.Int8        `json:"sign_count"`
	Aaguid                     []byte             `json:"aaguid"`
	BackupEligible             bool               `json:"backup_eligible"`
	BackupState                bool               `json:"backup_state"`
	CredentialFlagsInitialized bool               `json:"credential_flags_initialized"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	RevokedAt                  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt                 pgtype.Timestamptz `json:"last_used_at"`
	CredentialLabel            pgtype.Text        `json:"credential_label"`
}

type AuthPublicKey struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	PublicKey []byte             `json:"public_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthTotp struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	SecretSeed string             `json:"secret_seed"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthUser struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FiszkiCardProgress struct {
	UserID               pgtype.UUID        `json:"user_id"`
	QuestionID           pgtype.UUID        `json:"question_id"`
	Status               string             `json:"status"`
	TimesReviewed        int32              `json:"times_reviewed"`
	TimesCorrect         int32              `json:"times_correct"`
	Difficulty           float32            `json:"difficulty"`
	EaseFactor           float32            `json:"ease_factor"`
	IntervalDays         int32              `json:"interval_days"`
	ConsecutiveCorrect   int32              `json:"consecutive_correct"`
	ConsecutiveIncorrect int32              `json:"consecutive_incorrect"`
	LastReviewedAt       pgtype.Timestamptz `json:"last_reviewed_at"`
	NextReviewAt         pgtype.Timestamptz `json:"next_review_at"`
}

type FiszkiQuestion struct {
	ID             pgtype.UUID        `json:"id"`
	StudySetID     pgtype.UUID        `json:"study_set_id"`
	Position       int32              `json:"position"`
	QuestionType   string             `json:"question_type"`
	Prompt         string             `json:"prompt"`
	Answer         pgtype.Text        `json:"answer"`
	Choices        []string           `json:"choices"`
	CorrectIndices []int32            `json:"correct_indices"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FiszkiSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StudySetID       pgtype.UUID        `json:"study_set_id"`
	Mode             string             `json:"mode"`
	TotalQuestions   int32              `json:"total_questions"`
	CorrectAnswers   int32              `json:"correct_answers"`
	Score            int32              `json:"score"`
	TimeSpentSeconds int32              `json:"time_spent_seconds"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

type FiszkiSessionAnswer struct {
	ID              pgtype.UUID `json:"id"`
	SessionID       pgtype.UUID `json:"session_id"`
	QuestionID      pgtype.UUID `json:"question_id"`
	QuestionNumber  int32       `json:"question_number"`
	SelectedIndices []int32     `json:"selected_indices"`
	FlashcardResult pgtype.Text `json:"flashcard_result"`
	IsCorrect       bool        `json:"is_correct"`
	ResponseTimeMs  int32       `json:"response_time_ms"`
}

type FiszkiStudySet struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MonolithDek struct {
	ID              pgtype.UUID        `json:"id"`
	PasteID         pgtype.UUID        `json:"paste_id"`
	DeviceKeyID     pgtype.UUID        `json:"device_key_id"`
	WrappedDek      []byte             `json:"wrapped_dek"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	IsPasswordBased pgtype.Bool        `json:"is_password_based"`
}

type MonolithDropSession struct {
	ID          pgtype.UUID        `json:"id"`
	HostUserID  pgtype.UUID        `json:"host_user_id"`
	GuestUserID pgtype.UUID        `json:"guest_user_id"`
	PeerHost    string             `json:"peer_host"`
	PeerGuest   pgtype.Text        `json:"peer_guest"`
	JoinSecret  string             `json:"join_secret"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MonolithPaste struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       []byte             `json:"title"`
	Content     []byte             `json:"content"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	BurnedAt    pgtype.Timestamptz `json:"burned_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IsEncrypted pgtype.Bool        `json:"is_encrypted"`
	VaultOnly   bool               `json:"vault_only"`
}

type MonolithPasteShare struct {
	ID                  pgtype.UUID        `json:"id"`
	PasteID             pgtype.UUID        `json:"paste_id"`
	PublicToken         string             `json:"public_token"`
	VisibilityMode      string             `json:"visibility_mode"`
	ShareWrapNonce      []byte             `json:"share_wrap_nonce"`
	ShareWrapCiphertext []byte             `json:"share_wrap_ciphertext"`
	PasswordSalt        []byte             `json:"password_salt"`
	PasswordMemoryKib   pgtype.Int4        `json:"password_memory_kib"`
	PasswordIterations  pgtype.Int4        `json:"password_iterations"`
	PasswordParallelism pgtype.Int4        `json:"password_parallelism"`
	PasswordKeyLength   pgtype.Int4        `json:"password_key_length"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
