// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCredential struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CredentialID    []byte             `json:"credential_id"`
	PublicKey       []byte             `json:"public_key"`
	SignCount       pgtype.Int8        `json:"sign_count"`
	Aaguid          []byte             `json:"aaguid"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CredentialLabel pgtype.Text        `json:"credential_label"`
}

type AuthPublicKey struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	PublicKey []byte             `json:"public_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthTotp struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	SecretSeed string             `json:"secret_seed"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthUser struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MonolithDek struct {
	ID              pgtype.UUID        `json:"id"`
	PasteID         pgtype.UUID        `json:"paste_id"`
	DeviceKeyID     pgtype.UUID        `json:"device_key_id"`
	WrappedDek      []byte             `json:"wrapped_dek"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	IsPasswordBased pgtype.Bool        `json:"is_password_based"`
}

type MonolithPaste struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       []byte             `json:"title"`
	Content     []byte             `json:"content"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	BurnedAt    pgtype.Timestamptz `json:"burned_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IsEncrypted pgtype.Bool        `json:"is_encrypted"`
}

type MonolithPasteShare struct {
	ID                  pgtype.UUID        `json:"id"`
	PasteID             pgtype.UUID        `json:"paste_id"`
	PublicToken         string             `json:"public_token"`
	VisibilityMode      string             `json:"visibility_mode"`
	ShareWrapNonce      []byte             `json:"share_wrap_nonce"`
	ShareWrapCiphertext []byte             `json:"share_wrap_ciphertext"`
	PasswordSalt        []byte             `json:"password_salt"`
	PasswordMemoryKib   pgtype.Int4        `json:"password_memory_kib"`
	PasswordIterations  pgtype.Int4        `json:"password_iterations"`
	PasswordParallelism pgtype.Int4        `json:"password_parallelism"`
	PasswordKeyLength   pgtype.Int4        `json:"password_key_length"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
