// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pastes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const burnPasteForUser = `-- name: BurnPasteForUser :execrows
UPDATE monolith_paste
SET title = '\x'::bytea,
    content = '\x'::bytea,
    burned_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND (octet_length(title) > 0 OR octet_length(content) > 0)
`

type BurnPasteForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) BurnPasteForUser(ctx context.Context, arg BurnPasteForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, burnPasteForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchPasteContentByPasteID = `-- name: FetchPasteContentByPasteID :one
SELECT 
    p.id, 
    p.title AS encrypted_title, 
    p.content AS encrypted_content, 
    p.expires_at,
    p.is_encrypted,
    p.vault_only,
    d.wrapped_dek,
    d.is_password_based
FROM monolith_paste p
LEFT JOIN monolith_dek d ON p.id = d.paste_id
  AND (
    $3::uuid IS NOT NULL
    AND d.device_key_id = $3::uuid
  )
WHERE p.id = $1 
  AND p.user_id = $2
`

type FetchPasteContentByPasteIDParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DeviceKeyID pgtype.UUID `json:"device_key_id"`
}

type FetchPasteContentByPasteIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	EncryptedTitle   []byte             `json:"encrypted_title"`
	EncryptedContent []byte             `json:"encrypted_content"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	IsEncrypted      pgtype.Bool        `json:"is_encrypted"`
	VaultOnly        bool               `json:"vault_only"`
	WrappedDek       []byte             `json:"wrapped_dek"`
	IsPasswordBased  pgtype.Bool        `json:"is_password_based"`
}

func (q *Queries) FetchPasteContentByPasteID(ctx context.Context, arg FetchPasteContentByPasteIDParams) (FetchPasteContentByPasteIDRow, error) {
	row := q.db.QueryRow(ctx, fetchPasteContentByPasteID, arg.ID, arg.UserID, arg.DeviceKeyID)
	var i FetchPasteContentByPasteIDRow
	err := row.Scan(
		&i.ID,
		&i.EncryptedTitle,
		&i.EncryptedContent,
		&i.ExpiresAt,
		&i.IsEncrypted,
		&i.VaultOnly,
		&i.WrappedDek,
		&i.IsPasswordBased,
	)
	return i, err
}

const fetchPasteDekCoverageActiveForUser = `-- name: FetchPasteDekCoverageActiveForUser :many
SELECT 
  p.id AS paste_id,
  p.created_at,
  p.expires_at,
  p.is_encrypted,
  p.vault_only,
  false AS payload_wiped,
  COALESCE(string_agg(d.device_key_id::text, ',' ORDER BY d.device_key_id), '')::text AS device_key_ids_csv
FROM monolith_paste p
LEFT JOIN monolith_dek d ON d.paste_id = p.id
WHERE p.user_id = $1
  AND (octet_length(p.title) > 0 OR octet_length(p.content) > 0)
GROUP BY p.id
ORDER BY p.created_at DESC
`

type FetchPasteDekCoverageActiveForUserRow struct {
	PasteID         pgtype.UUID        `json:"paste_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsEncrypted     pgtype.Bool        `json:"is_encrypted"`
	VaultOnly       bool               `json:"vault_only"`
	PayloadWiped    bool               `json:"payload_wiped"`
	DeviceKeyIdsCsv string             `json:"device_key_ids_csv"`
}

func (q *Queries) FetchPasteDekCoverageActiveForUser(ctx context.Context, userID pgtype.UUID) ([]FetchPasteDekCoverageActiveForUserRow, error) {
	rows, err := q.db.Query(ctx, fetchPasteDekCoverageActiveForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPasteDekCoverageActiveForUserRow
	for rows.Next() {
		var i FetchPasteDekCoverageActiveForUserRow
		if err := rows.Scan(
			&i.PasteID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsEncrypted,
			&i.VaultOnly,
			&i.PayloadWiped,
			&i.DeviceKeyIdsCsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchPasteDekCoverageBurnedForUser = `-- name: FetchPasteDekCoverageBurnedForUser :many
SELECT 
  p.id AS paste_id,
  p.created_at,
  p.expires_at,
  p.burned_at,
  p.is_encrypted,
  p.vault_only,
  COALESCE(string_agg(d.device_key_id::text, ',' ORDER BY d.device_key_id), '')::text AS device_key_ids_csv
FROM monolith_paste p
LEFT JOIN monolith_dek d ON d.paste_id = p.id
WHERE p.user_id = $1
  AND octet_length(p.title) = 0
  AND octet_length(p.content) = 0
GROUP BY p.id
ORDER BY p.created_at DESC
`

type FetchPasteDekCoverageBurnedForUserRow struct {
	PasteID         pgtype.UUID        `json:"paste_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	BurnedAt        pgtype.Timestamptz `json:"burned_at"`
	IsEncrypted     pgtype.Bool        `json:"is_encrypted"`
	VaultOnly       bool               `json:"vault_only"`
	DeviceKeyIdsCsv string             `json:"device_key_ids_csv"`
}

func (q *Queries) FetchPasteDekCoverageBurnedForUser(ctx context.Context, userID pgtype.UUID) ([]FetchPasteDekCoverageBurnedForUserRow, error) {
	rows, err := q.db.Query(ctx, fetchPasteDekCoverageBurnedForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPasteDekCoverageBurnedForUserRow
	for rows.Next() {
		var i FetchPasteDekCoverageBurnedForUserRow
		if err := rows.Scan(
			&i.PasteID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.BurnedAt,
			&i.IsEncrypted,
			&i.VaultOnly,
			&i.DeviceKeyIdsCsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchPasteMetadataByDeviceID = `-- name: FetchPasteMetadataByDeviceID :many
SELECT 
    p.id AS paste_id, 
    p.title AS encrypted_title, 
    p.created_at,
    p.expires_at,
    p.is_encrypted,
    p.vault_only,
    d.wrapped_dek,
    d.is_password_based
FROM monolith_paste p
LEFT JOIN monolith_dek d ON p.id = d.paste_id
  AND (
    $2::uuid IS NOT NULL
    AND d.device_key_id = $2::uuid
  )
WHERE p.user_id = $1
  AND (octet_length(p.title) > 0 OR octet_length(p.content) > 0)
ORDER BY p.created_at DESC
`

type FetchPasteMetadataByDeviceIDParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DeviceKeyID pgtype.UUID `json:"device_key_id"`
}

type FetchPasteMetadataByDeviceIDRow struct {
	PasteID         pgtype.UUID        `json:"paste_id"`
	EncryptedTitle  []byte             `json:"encrypted_title"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsEncrypted     pgtype.Bool        `json:"is_encrypted"`
	VaultOnly       bool               `json:"vault_only"`
	WrappedDek      []byte             `json:"wrapped_dek"`
	IsPasswordBased pgtype.Bool        `json:"is_password_based"`
}

func (q *Queries) FetchPasteMetadataByDeviceID(ctx context.Context, arg FetchPasteMetadataByDeviceIDParams) ([]FetchPasteMetadataByDeviceIDRow, error) {
	rows, err := q.db.Query(ctx, fetchPasteMetadataByDeviceID, arg.UserID, arg.DeviceKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPasteMetadataByDeviceIDRow
	for rows.Next() {
		var i FetchPasteMetadataByDeviceIDRow
		if err := rows.Scan(
			&i.PasteID,
			&i.EncryptedTitle,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsEncrypted,
			&i.VaultOnly,
			&i.WrappedDek,
			&i.IsPasswordBased,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchPasteVaultOnlyForOwner = `-- name: FetchPasteVaultOnlyForOwner :one
SELECT vault_only
FROM monolith_paste
WHERE id = $1 AND user_id = $2
`

type FetchPasteVaultOnlyForOwnerParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) FetchPasteVaultOnlyForOwner(ctx context.Context, arg FetchPasteVaultOnlyForOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, fetchPasteVaultOnlyForOwner, arg.ID, arg.UserID)
	var vault_only bool
	err := row.Scan(&vault_only)
	return vault_only, err
}

const getPasteShareByToken = `-- name: GetPasteShareByToken :one
SELECT
  p.id AS paste_id,
  p.title AS encrypted_title,
  p.content AS encrypted_content,
  p.expires_at AS paste_expires_at,
  p.created_at AS paste_created_at,
  p.is_encrypted,
  p.vault_only,
  p.burned_at,
  u.email AS owner_email,
  s.public_token,
  s.visibility_mode,
  s.share_wrap_nonce,
  s.share_wrap_ciphertext,
  s.password_salt,
  s.password_memory_kib,
  s.password_iterations,
  s.password_parallelism,
  s.password_key_length,
  s.expires_at AS share_expires_at,
  s.revoked_at
FROM monolith_paste_share s
JOIN monolith_paste p ON p.id = s.paste_id
JOIN auth_users u ON u.id = p.user_id
WHERE s.public_token = $1
`

type GetPasteShareByTokenRow struct {
	PasteID             pgtype.UUID        `json:"paste_id"`
	EncryptedTitle      []byte             `json:"encrypted_title"`
	EncryptedContent    []byte             `json:"encrypted_content"`
	PasteExpiresAt      pgtype.Timestamptz `json:"paste_expires_at"`
	PasteCreatedAt      pgtype.Timestamptz `json:"paste_created_at"`
	IsEncrypted         pgtype.Bool        `json:"is_encrypted"`
	VaultOnly           bool               `json:"vault_only"`
	BurnedAt            pgtype.Timestamptz `json:"burned_at"`
	OwnerEmail          string             `json:"owner_email"`
	PublicToken         string             `json:"public_token"`
	VisibilityMode      string             `json:"visibility_mode"`
	ShareWrapNonce      []byte             `json:"share_wrap_nonce"`
	ShareWrapCiphertext []byte             `json:"share_wrap_ciphertext"`
	PasswordSalt        []byte             `json:"password_salt"`
	PasswordMemoryKib   pgtype.Int4        `json:"password_memory_kib"`
	PasswordIterations  pgtype.Int4        `json:"password_iterations"`
	PasswordParallelism pgtype.Int4        `json:"password_parallelism"`
	PasswordKeyLength   pgtype.Int4        `json:"password_key_length"`
	ShareExpiresAt      pgtype.Timestamptz `json:"share_expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetPasteShareByToken(ctx context.Context, publicToken string) (GetPasteShareByTokenRow, error) {
	row := q.db.QueryRow(ctx, getPasteShareByToken, publicToken)
	var i GetPasteShareByTokenRow
	err := row.Scan(
		&i.PasteID,
		&i.EncryptedTitle,
		&i.EncryptedContent,
		&i.PasteExpiresAt,
		&i.PasteCreatedAt,
		&i.IsEncrypted,
		&i.VaultOnly,
		&i.BurnedAt,
		&i.OwnerEmail,
		&i.PublicToken,
		&i.VisibilityMode,
		&i.ShareWrapNonce,
		&i.ShareWrapCiphertext,
		&i.PasswordSalt,
		&i.PasswordMemoryKib,
		&i.PasswordIterations,
		&i.PasswordParallelism,
		&i.PasswordKeyLength,
		&i.ShareExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertEncryptedPayload = `-- name: InsertEncryptedPayload :one
INSERT INTO monolith_paste (user_id, title, content, expires_at, is_encrypted, vault_only)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertEncryptedPayloadParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Title       []byte             `json:"title"`
	Content     []byte             `json:"content"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	IsEncrypted pgtype.Bool        `json:"is_encrypted"`
	VaultOnly   bool               `json:"vault_only"`
}

func (q *Queries) InsertEncryptedPayload(ctx context.Context, arg InsertEncryptedPayloadParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertEncryptedPayload,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ExpiresAt,
		arg.IsEncrypted,
		arg.VaultOnly,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertWrappedDEKs = `-- name: InsertWrappedDEKs :exec
INSERT INTO monolith_dek (paste_id, device_key_id, wrapped_dek, is_password_based)
SELECT 
    $1 AS paste_id, 
    unnest($2::uuid[]) AS device_key_id, 
    unnest($3::bytea[]) AS wrapped_dek,
    unnest($4::boolean[]) AS is_password_based
`

type InsertWrappedDEKsParams struct {
	PasteID          pgtype.UUID   `json:"paste_id"`
	DeviceKeyIds     []pgtype.UUID `json:"device_key_ids"`
	WrappedDeks      [][]byte      `json:"wrapped_deks"`
	IsPasswordBaseds []bool        `json:"is_password_baseds"`
}

func (q *Queries) InsertWrappedDEKs(ctx context.Context, arg InsertWrappedDEKsParams) error {
	_, err := q.db.Exec(ctx, insertWrappedDEKs,
		arg.PasteID,
		arg.DeviceKeyIds,
		arg.WrappedDeks,
		arg.IsPasswordBaseds,
	)
	return err
}

const listRecentSharedPastesByOwner = `-- name: ListRecentSharedPastesByOwner :many
SELECT
  p.id AS paste_id,
  p.title AS encrypted_title,
  p.created_at,
  p.expires_at,
  s.public_token,
  s.visibility_mode
FROM monolith_paste_share s
JOIN monolith_paste p ON p.id = s.paste_id
WHERE p.user_id = $1
  AND s.revoked_at IS NULL
  AND (s.expires_at IS NULL OR s.expires_at > NOW())
  AND (octet_length(p.title) > 0 OR octet_length(p.content) > 0)
ORDER BY p.created_at DESC
LIMIT 20
`

type ListRecentSharedPastesByOwnerRow struct {
	PasteID        pgtype.UUID        `json:"paste_id"`
	EncryptedTitle []byte             `json:"encrypted_title"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	PublicToken    string             `json:"public_token"`
	VisibilityMode string             `json:"visibility_mode"`
}

func (q *Queries) ListRecentSharedPastesByOwner(ctx context.Context, userID pgtype.UUID) ([]ListRecentSharedPastesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listRecentSharedPastesByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentSharedPastesByOwnerRow
	for rows.Next() {
		var i ListRecentSharedPastesByOwnerRow
		if err := rows.Scan(
			&i.PasteID,
			&i.EncryptedTitle,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.PublicToken,
			&i.VisibilityMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pasteHasCiphertext = `-- name: PasteHasCiphertext :one
SELECT (octet_length(title) > 0 OR octet_length(content) > 0) AS ok
FROM monolith_paste
WHERE id = $1 AND user_id = $2
`

type PasteHasCiphertextParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) PasteHasCiphertext(ctx context.Context, arg PasteHasCiphertextParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, pasteHasCiphertext, arg.ID, arg.UserID)
	var ok pgtype.Bool
	err := row.Scan(&ok)
	return ok, err
}

const pasteOwnedByUser = `-- name: PasteOwnedByUser :one
SELECT EXISTS(
  SELECT 1 FROM monolith_paste WHERE id = $1 AND user_id = $2
) AS ok
`

type PasteOwnedByUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) PasteOwnedByUser(ctx context.Context, arg PasteOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, pasteOwnedByUser, arg.ID, arg.UserID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const revokePasteShareForOwner = `-- name: RevokePasteShareForOwner :execrows
UPDATE monolith_paste_share s
SET revoked_at = NOW(),
    updated_at = NOW()
FROM monolith_paste p
WHERE s.paste_id = p.id
  AND s.paste_id = $1
  AND p.user_id = $2
  AND s.revoked_at IS NULL
`

type RevokePasteShareForOwnerParams struct {
	PasteID pgtype.UUID `json:"paste_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokePasteShareForOwner(ctx context.Context, arg RevokePasteShareForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePasteShareForOwner, arg.PasteID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPasteShare = `-- name: UpsertPasteShare :exec
INSERT INTO monolith_paste_share (
  paste_id,
  public_token,
  visibility_mode,
  share_wrap_nonce,
  share_wrap_ciphertext,
  password_salt,
  password_memory_kib,
  password_iterations,
  password_parallelism,
  password_key_length,
  expires_at,
  revoked_at,
  created_by,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  NULL,
  $12,
  NOW()
)
ON CONFLICT (paste_id)
DO UPDATE SET
  public_token = EXCLUDED.public_token,
  visibility_mode = EXCLUDED.visibility_mode,
  share_wrap_nonce = EXCLUDED.share_wrap_nonce,
  share_wrap_ciphertext = EXCLUDED.share_wrap_ciphertext,
  password_salt = EXCLUDED.password_salt,
  password_memory_kib = EXCLUDED.password_memory_kib,
  password_iterations = EXCLUDED.password_iterations,
  password_parallelism = EXCLUDED.password_parallelism,
  password_key_length = EXCLUDED.password_key_length,
  expires_at = EXCLUDED.expires_at,
  revoked_at = NULL,
  created_by = EXCLUDED.created_by,
  updated_at = NOW()
`

type UpsertPasteShareParams struct {
	PasteID             pgtype.UUID        `json:"paste_id"`
	PublicToken         string             `json:"public_token"`
	VisibilityMode      string             `json:"visibility_mode"`
	ShareWrapNonce      []byte             `json:"share_wrap_nonce"`
	ShareWrapCiphertext []byte             `json:"share_wrap_ciphertext"`
	PasswordSalt        []byte             `json:"password_salt"`
	PasswordMemoryKib   pgtype.Int4        `json:"password_memory_kib"`
	PasswordIterations  pgtype.Int4        `json:"password_iterations"`
	PasswordParallelism pgtype.Int4        `json:"password_parallelism"`
	PasswordKeyLength   pgtype.Int4        `json:"password_key_length"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
}

func (q *Queries) UpsertPasteShare(ctx context.Context, arg UpsertPasteShareParams) error {
	_, err := q.db.Exec(ctx, upsertPasteShare,
		arg.PasteID,
		arg.PublicToken,
		arg.VisibilityMode,
		arg.ShareWrapNonce,
		arg.ShareWrapCiphertext,
		arg.PasswordSalt,
		arg.PasswordMemoryKib,
		arg.PasswordIterations,
		arg.PasswordParallelism,
		arg.PasswordKeyLength,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const upsertWrappedDEK = `-- name: UpsertWrappedDEK :exec
INSERT INTO monolith_dek (paste_id, device_key_id, wrapped_dek)
VALUES ($1, $2, $3)
ON CONFLICT (paste_id, device_key_id)
DO UPDATE SET wrapped_dek = EXCLUDED.wrapped_dek
`

type UpsertWrappedDEKParams struct {
	PasteID     pgtype.UUID `json:"paste_id"`
	DeviceKeyID pgtype.UUID `json:"device_key_id"`
	WrappedDek  []byte      `json:"wrapped_dek"`
}

func (q *Queries) UpsertWrappedDEK(ctx context.Context, arg UpsertWrappedDEKParams) error {
	_, err := q.db.Exec(ctx, upsertWrappedDEK, arg.PasteID, arg.DeviceKeyID, arg.WrappedDek)
	return err
}

const wipeExpiredPastePayloadsForUser = `-- name: WipeExpiredPastePayloadsForUser :exec
UPDATE monolith_paste
SET title = '\x'::bytea, content = '\x'::bytea
WHERE user_id = $1
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
  AND (octet_length(title) > 0 OR octet_length(content) > 0)
`

func (q *Queries) WipeExpiredPastePayloadsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, wipeExpiredPastePayloadsForUser, userID)
	return err
}
