// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BurnPasteForUser(ctx context.Context, arg BurnPasteForUserParams) (int64, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (AuthCredential, error)
	CreateUser(ctx context.Context, email string) (AuthUser, error)
	DeviceKeyOwnedByUser(ctx context.Context, arg DeviceKeyOwnedByUserParams) (bool, error)
	FetchPasteContentByPasteID(ctx context.Context, arg FetchPasteContentByPasteIDParams) (FetchPasteContentByPasteIDRow, error)
	FetchPasteDekCoverageActiveForUser(ctx context.Context, userID pgtype.UUID) ([]FetchPasteDekCoverageActiveForUserRow, error)
	FetchPasteDekCoverageBurnedForUser(ctx context.Context, userID pgtype.UUID) ([]FetchPasteDekCoverageBurnedForUserRow, error)
	FetchPasteMetadataByDeviceID(ctx context.Context, arg FetchPasteMetadataByDeviceIDParams) ([]FetchPasteMetadataByDeviceIDRow, error)
	FetchPublicKeysByUserID(ctx context.Context, userID pgtype.UUID) ([]FetchPublicKeysByUserIDRow, error)
	GetActiveCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthCredential, error)
	GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (AuthCredential, error)
	GetCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthCredential, error)
	GetPasteShareByToken(ctx context.Context, publicToken string) (GetPasteShareByTokenRow, error)
	GetTOTPByEmail(ctx context.Context, email string) (AuthTotp, error)
	GetTOTPByUserID(ctx context.Context, userID pgtype.UUID) (AuthTotp, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (AuthUser, error)
	InsertEncryptedPayload(ctx context.Context, arg InsertEncryptedPayloadParams) (pgtype.UUID, error)
	InsertWrappedDEKs(ctx context.Context, arg InsertWrappedDEKsParams) error
	ListRecentSharedPastesByOwner(ctx context.Context, userID pgtype.UUID) ([]ListRecentSharedPastesByOwnerRow, error)
	PasteHasCiphertext(ctx context.Context, arg PasteHasCiphertextParams) (pgtype.Bool, error)
	PasteOwnedByUser(ctx context.Context, arg PasteOwnedByUserParams) (bool, error)
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (pgtype.UUID, error)
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error
	RevokePasteShareForOwner(ctx context.Context, arg RevokePasteShareForOwnerParams) (int64, error)
	SetTOTPActive(ctx context.Context, userID pgtype.UUID) error
	TouchCredentialLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateCredentialLabel(ctx context.Context, arg UpdateCredentialLabelParams) error
	UpdateCredentialSignCount(ctx context.Context, arg UpdateCredentialSignCountParams) error
	UpsertPasteShare(ctx context.Context, arg UpsertPasteShareParams) error
	UpsertTOTPSecret(ctx context.Context, arg UpsertTOTPSecretParams) (AuthTotp, error)
	UpsertWrappedDEK(ctx context.Context, arg UpsertWrappedDEKParams) error
	WipeExpiredPastePayloadsForUser(ctx context.Context, userID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
