// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BurnPasteForUser(ctx context.Context, arg BurnPasteForUserParams) (int64, error)
	CloseDropSessionForHost(ctx context.Context, arg CloseDropSessionForHostParams) (MonolithDropSession, error)
	CountFiszkiStudySetsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (AuthCredential, error)
	CreateDropSession(ctx context.Context, arg CreateDropSessionParams) (MonolithDropSession, error)
	CreateFiszkiSession(ctx context.Context, arg CreateFiszkiSessionParams) (CreateFiszkiSessionRow, error)
	CreateFiszkiStudySet(ctx context.Context, arg CreateFiszkiStudySetParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, email string) (AuthUser, error)
	DeleteFiszkiCardProgressForSet(ctx context.Context, arg DeleteFiszkiCardProgressForSetParams) (int64, error)
	DeleteFiszkiStudySet(ctx context.Context, arg DeleteFiszkiStudySetParams) (int64, error)
	DeviceKeyOwnedByUser(ctx context.Context, arg DeviceKeyOwnedByUserParams) (bool, error)
	FetchPasteContentByPasteID(ctx context.Context, arg FetchPasteContentByPasteIDParams) (FetchPasteContentByPasteIDRow, error)
	FetchPasteDekCoverageActiveForUser(ctx context.Context, userID pgtype.UUID) ([]FetchPasteDekCoverageActiveForUserRow, error)
	FetchPasteDekCoverageBurnedForUser(ctx context.Context, userID pgtype.UUID) ([]FetchPasteDekCoverageBurnedForUserRow, error)
	FetchPasteMetadataByDeviceID(ctx context.Context, arg FetchPasteMetadataByDeviceIDParams) ([]FetchPasteMetadataByDeviceIDRow, error)
	FetchPasteVaultOnlyForOwner(ctx context.Context, arg FetchPasteVaultOnlyForOwnerParams) (bool, error)
	FetchPublicKeysByUserID(ctx context.Context, userID pgtype.UUID) ([]FetchPublicKeysByUserIDRow, error)
	GetActiveCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthCredential, error)
	GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (AuthCredential, error)
	GetCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthCredential, error)
	GetDropSessionByJoinSecret(ctx context.Context, joinSecret string) (MonolithDropSession, error)
	GetDropSessionByJoinSecretRaw(ctx context.Context, joinSecret string) (MonolithDropSession, error)
	GetDropSessionForHost(ctx context.Context, arg GetDropSessionForHostParams) (MonolithDropSession, error)
	GetDropSessionForParticipant(ctx context.Context, arg GetDropSessionForParticipantParams) (MonolithDropSession, error)
	GetFiszkiOverallStats(ctx context.Context, userID pgtype.UUID) (GetFiszkiOverallStatsRow, error)
	GetFiszkiSession(ctx context.Context, arg GetFiszkiSessionParams) (GetFiszkiSessionRow, error)
	GetFiszkiStudySet(ctx context.Context, arg GetFiszkiStudySetParams) (FiszkiStudySet, error)
	GetPasteShareByToken(ctx context.Context, publicToken string) (GetPasteShareByTokenRow, error)
	GetTOTPByEmail(ctx context.Context, email string) (AuthTotp, error)
	GetTOTPByUserID(ctx context.Context, userID pgtype.UUID) (AuthTotp, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (AuthUser, error)
	InsertEncryptedPayload(ctx context.Context, arg InsertEncryptedPayloadParams) (pgtype.UUID, error)
	InsertFiszkiQuestions(ctx context.Context, arg []InsertFiszkiQuestionsParams) (int64, error)
	InsertFiszkiSessionAnswers(ctx context.Context, arg []InsertFiszkiSessionAnswersParams) (int64, error)
	InsertWrappedDEKs(ctx context.Context, arg InsertWrappedDEKsParams) error
	JoinDropSession(ctx context.Context, arg JoinDropSessionParams) (MonolithDropSession, error)
	ListFiszkiCardProgressBySet(ctx context.Context, arg ListFiszkiCardProgressBySetParams) ([]FiszkiCardProgress, error)
	ListFiszkiQuestionsBySet(ctx context.Context, studySetID pgtype.UUID) ([]FiszkiQuestion, error)
	ListFiszkiSessionAnswers(ctx context.Context, sessionID pgtype.UUID) ([]ListFiszkiSessionAnswersRow, error)
	ListFiszkiStudySetsWithStats(ctx context.Context, userID pgtype.UUID) ([]ListFiszkiStudySetsWithStatsRow, error)
	ListRecentSharedPastesByOwner(ctx context.Context, userID pgtype.UUID) ([]ListRecentSharedPastesByOwnerRow, error)
	PasteHasCiphertext(ctx context.Context, arg PasteHasCiphertextParams) (pgtype.Bool, error)
	PasteOwnedByUser(ctx context.Context, arg PasteOwnedByUserParams) (bool, error)
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (pgtype.UUID, error)
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error
	RevokePasteShareForOwner(ctx context.Context, arg RevokePasteShareForOwnerParams) (int64, error)
	SetTOTPActive(ctx context.Context, userID pgtype.UUID) error
	TouchCredentialLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateCredentialFlags(ctx context.Context, arg UpdateCredentialFlagsParams) error
	UpdateCredentialLabel(ctx context.Context, arg UpdateCredentialLabelParams) error
	UpdateCredentialSignCount(ctx context.Context, arg UpdateCredentialSignCountParams) error
	UpsertFiszkiCardProgress(ctx context.Context, arg UpsertFiszkiCardProgressParams) error
	UpsertPasteShare(ctx context.Context, arg UpsertPasteShareParams) error
	UpsertTOTPSecret(ctx context.Context, arg UpsertTOTPSecretParams) (AuthTotp, error)
	UpsertWrappedDEK(ctx context.Context, arg UpsertWrappedDEKParams) error
	WipeExpiredPastePayloadsForUser(ctx context.Context, userID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
