// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTOTPByEmail = `-- name: GetTOTPByEmail :one
SELECT t.id, t.user_id, t.secret_seed, t.is_active, t.created_at
FROM auth_totp t
INNER JOIN auth_users u ON u.id = t.user_id
WHERE u.email = $1
LIMIT 1
`

func (q *Queries) GetTOTPByEmail(ctx context.Context, email string) (AuthTotp, error) {
	row := q.db.QueryRow(ctx, getTOTPByEmail, email)
	var i AuthTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretSeed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTOTPByUserID = `-- name: GetTOTPByUserID :one
SELECT id, user_id, secret_seed, is_active, created_at
FROM auth_totp
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetTOTPByUserID(ctx context.Context, userID pgtype.UUID) (AuthTotp, error) {
	row := q.db.QueryRow(ctx, getTOTPByUserID, userID)
	var i AuthTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretSeed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const setTOTPActive = `-- name: SetTOTPActive :exec
UPDATE auth_totp
SET is_active = TRUE
WHERE user_id = $1
`

func (q *Queries) SetTOTPActive(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setTOTPActive, userID)
	return err
}

const upsertTOTPSecret = `-- name: UpsertTOTPSecret :one
INSERT INTO auth_totp (user_id, secret_seed, is_active)
VALUES ($1, $2, FALSE)
ON CONFLICT (user_id) DO UPDATE SET
    secret_seed = EXCLUDED.secret_seed,
    is_active = FALSE,
    created_at = NOW()
RETURNING id, user_id, secret_seed, is_active, created_at
`

type UpsertTOTPSecretParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	SecretSeed string      `json:"secret_seed"`
}

func (q *Queries) UpsertTOTPSecret(ctx context.Context, arg UpsertTOTPSecretParams) (AuthTotp, error) {
	row := q.db.QueryRow(ctx, upsertTOTPSecret, arg.UserID, arg.SecretSeed)
	var i AuthTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretSeed,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
