// Code generated by tygo. DO NOT EDIT.

//////////
// source: login.go

export interface LoginFinishResponse {
  credentialId: string;
  redirectTo: string;
  requireLocalPasskeyEnrollment: boolean;
}

//////////
// source: registration.go

export interface RegistrationFinishRequest {
  attestation: unknown;
  credentialLabel?: string;
}

//////////
// source: webauthnuser.go

export interface WebAuthnUser {
  AuthUser: any /* database.AuthUser */;
  Credentials: any /* webauthn.Credential */[];
}
