// Code generated by tygo. DO NOT EDIT.

//////////
// source: paste.go

/**
 * EncryptedPasteCreateRequest is the JSON body for POST /pastes (base64 fields).
 */
export interface EncryptedPasteCreateRequest {
  encrypted_title: string;
  encrypted_content: string;
  wrapped_deks: WrappedDEKEntry[];
  expires_in_seconds?: number /* int */;
  is_encrypted: boolean;
  vault_only?: boolean;
}
/**
 * WrappedDEKEntry maps a device key to its wrapped DEK blob (base64).
 */
export interface WrappedDEKEntry {
  device_key_id: string;
  wrapped_dek: string;
}
/**
 * PasteContentResponse is returned by GET /pastes/{id}.
 */
export interface PasteContentResponse {
  id: string;
  encrypted_title: string;
  encrypted_content: string;
  wrapped_dek: string;
  is_encrypted: boolean;
  vault_only: boolean;
}
/**
 * PasteMetadataResponse is one row from GET /pastes.
 */
export interface PasteMetadataResponse {
  paste_id: string;
  encrypted_title: string;
  created_at: string;
  wrapped_dek: string;
  expires_at?: string;
  payload_wiped: boolean;
  is_encrypted: boolean;
  vault_only: boolean;
}
/**
 * DekCoveragePasteRow is one paste entry in DekCoverageResponse.
 */
export interface DekCoveragePasteRow {
  paste_id: string;
  created_at: string;
  expires_at?: string;
  payload_wiped: boolean;
  device_key_ids_with_dek: string[];
  is_encrypted: boolean;
  vault_only: boolean;
}
/**
 * DekCoverageResponse is returned by GET /pastes/dek-coverage.
 */
export interface DekCoverageResponse {
  devices: DeviceKeyResponse[];
  pastes: DekCoveragePasteRow[];
}
/**
 * BurnedPasteRow is one paste entry in BurnedPastesResponse.
 */
export interface BurnedPasteRow {
  paste_id: string;
  created_at: string;
  expires_at?: string;
  burned_at?: string;
  reason: string;
  device_key_ids_with_dek: string[];
  vault_only: boolean;
}
/**
 * BurnedPastesResponse is returned by GET /pastes/burned.
 */
export interface BurnedPastesResponse {
  devices: DeviceKeyResponse[];
  pastes: BurnedPasteRow[];
}
export type ShareVisibilityMode = string;
export const ShareVisibilityPublic: ShareVisibilityMode = "public";
export const ShareVisibilityPassword: ShareVisibilityMode = "password";
/**
 * SharePasswordKDF contains Argon2id parameters and salt used for deriving key material.
 */
export interface SharePasswordKDF {
  salt: string;
  memory_kib: number /* int */;
  iterations: number /* int */;
  parallelism: number /* int */;
  derived_key_length: number /* int */;
}
/**
 * UpsertPasteShareRequest is the JSON body for POST /pastes/{id}/share.
 */
export interface UpsertPasteShareRequest {
  visibility_mode: ShareVisibilityMode;
  share_wrap_nonce?: string;
  share_wrap_blob?: string;
  password_kdf?: SharePasswordKDF;
  expires_in_seconds?: number /* int */;
}
/**
 * UpsertPasteShareResponse returns the opaque share token and URL.
 */
export interface UpsertPasteShareResponse {
  token: string;
  url: string;
}
/**
 * SharedPasteResponse is returned by GET /shared-pastes/{token}.
 */
export interface SharedPasteResponse {
  token: string;
  visibility_mode: ShareVisibilityMode;
  encrypted_title: string;
  encrypted_content: string;
  share_wrap_nonce?: string;
  share_wrap_blob?: string;
  password_kdf?: SharePasswordKDF;
  expires_at?: string;
  created_at: string;
  owner_email: string;
  paste_id: string;
  is_encrypted: boolean;
}
/**
 * SharedPasteMetadataResponse is one row from GET /pastes/shared/recent.
 */
export interface SharedPasteMetadataResponse {
  paste_id: string;
  public_token: string;
  visibility_mode: ShareVisibilityMode;
  encrypted_title: string;
  created_at: string;
  expires_at?: string;
}
/**
 * RegisterDeviceRequest is the JSON body for POST /devices.
 */
export interface RegisterDeviceRequest {
  public_key: string;
}
/**
 * RegisterDeviceResponse is returned after POST /devices.
 */
export interface RegisterDeviceResponse {
  device_key_id: string;
}
/**
 * DeviceKeyResponse is one row from GET /devices/keys.
 */
export interface DeviceKeyResponse {
  device_key_id: string;
  public_key: string;
}
