// Code generated by tygo. DO NOT EDIT.

//////////
// source: drop_session.go

/**
 * CreateDropSessionRequest is optional body for POST /v1/drop/sessions.
 */
export interface CreateDropSessionRequest {
  expires_in_seconds?: number /* int64 */;
}
/**
 * CreateDropSessionResponse is returned when a host creates a session.
 */
export interface CreateDropSessionResponse {
  session_id: string;
  peer_id: string;
  remote_peer_id?: string;
  role: string;
  join_secret: string;
  expires_at: string;
  peer_host: string;
  peer_guest?: string;
}
/**
 * GetDropSessionResponse is returned from GET /v1/drop/sessions/{id} (join_secret omitted).
 */
export interface GetDropSessionResponse {
  session_id: string;
  peer_host: string;
  peer_guest?: string;
  expires_at: string;
  created_at: string;
  closed_at?: string;
}
/**
 * JoinDropSessionRequest is the body for POST /v1/drop/sessions/join.
 */
export interface JoinDropSessionRequest {
  join_secret: string;
}
/**
 * JoinDropSessionResponse is returned after a guest joins.
 */
export interface JoinDropSessionResponse {
  session_id: string;
  peer_id: string;
  remote_peer_id: string;
  role: string;
  expires_at: string;
}
/**
 * CloseDropSessionResponse confirms close.
 */
export interface CloseDropSessionResponse {
  session_id: string;
  closed: boolean;
}

//////////
// source: health.go

/**
 * HealthResponse is a minimal JSON shape for future drop API health checks.
 * Tygo emits apps/monolith-drop/src/types/backend.d.ts from this package.
 */
export interface HealthResponse {
  ok: boolean;
}
