// Code generated by tygo. DO NOT EDIT.

//////////
// source: fiszki.go

/**
 * QuestionInput is one question in POST /sets.
 */
export interface QuestionInput {
  type: string;
  prompt: string;
  answer?: string;
  choices?: string[];
  correct_indices?: number /* int */[];
}
/**
 * CreateStudySetRequest is the JSON body for POST /sets.
 */
export interface CreateStudySetRequest {
  name: string;
  description: string;
  questions: QuestionInput[];
}
/**
 * CreateStudySetResponse is returned after POST /sets.
 */
export interface CreateStudySetResponse {
  id: string;
}
/**
 * StudySetSummary is one row from GET /sets and GET /stats.
 */
export interface StudySetSummary {
  id: string;
  name: string;
  description: string;
  created_at: string;
  question_count: number /* int64 */;
  flashcard_count: number /* int64 */;
  known_count: number /* int64 */;
  unknown_count: number /* int64 */;
  session_count: number /* int64 */;
  best_score: number /* int64 */;
  average_score: number /* float64 */;
  total_time_spent_seconds: number /* int64 */;
  last_attempt_at?: string;
}
/**
 * QuestionResponse is one question inside GET /sets/{id}.
 */
export interface QuestionResponse {
  id: string;
  type: string;
  prompt: string;
  answer?: string;
  choices?: string[];
  correct_indices?: number /* int */[];
}
/**
 * CardProgressResponse is per-card spaced-repetition state inside GET /sets/{id}.
 */
export interface CardProgressResponse {
  question_id: string;
  status: string;
  times_reviewed: number /* int */;
  times_correct: number /* int */;
  difficulty: number /* float32 */;
  ease_factor: number /* float32 */;
  interval_days: number /* int */;
  consecutive_correct: number /* int */;
  consecutive_incorrect: number /* int */;
  last_reviewed_at?: string;
  next_review_at?: string;
}
/**
 * StudySetDetailResponse is returned by GET /sets/{id}.
 */
export interface StudySetDetailResponse {
  id: string;
  name: string;
  description: string;
  created_at: string;
  questions: QuestionResponse[];
  progress: CardProgressResponse[];
}
/**
 * SessionAnswerInput is one answered question in POST /sessions.
 */
export interface SessionAnswerInput {
  question_id: string;
  question_number: number /* int */;
  selected_indices?: number /* int */[];
  flashcard_result?: string;
  response_time_ms: number /* int */;
}
/**
 * CreateSessionRequest is the JSON body for POST /sessions.
 */
export interface CreateSessionRequest {
  study_set_id: string;
  mode: string;
  started_at: string;
  time_spent_seconds: number /* int */;
  answers: SessionAnswerInput[];
}
/**
 * CreateSessionResponse is returned after POST /sessions.
 */
export interface CreateSessionResponse {
  id: string;
  score: number /* int */;
  correct_answers: number /* int */;
  total_questions: number /* int */;
}
/**
 * SessionAnswerResponse is one row in SessionReportResponse.
 */
export interface SessionAnswerResponse {
  question_number: number /* int */;
  question_id: string;
  type: string;
  prompt: string;
  answer?: string;
  choices?: string[];
  correct_indices?: number /* int */[];
  selected_indices?: number /* int */[];
  flashcard_result?: string;
  is_correct: boolean;
  response_time_ms: number /* int */;
}
/**
 * SessionReportResponse is returned by GET /sessions/{id}.
 */
export interface SessionReportResponse {
  id: string;
  study_set_id: string;
  study_set_name: string;
  mode: string;
  total_questions: number /* int */;
  correct_answers: number /* int */;
  score: number /* int */;
  time_spent_seconds: number /* int */;
  started_at: string;
  ended_at: string;
  answers: SessionAnswerResponse[];
}
/**
 * OverallStatsResponse is returned by GET /stats.
 */
export interface OverallStatsResponse {
  studied_set_count: number /* int64 */;
  session_count: number /* int64 */;
  average_score: number /* float64 */;
  best_score: number /* int64 */;
  total_time_spent_seconds: number /* int64 */;
  total_questions_answered: number /* int64 */;
  total_correct_answers: number /* int64 */;
  sets: StudySetSummary[];
}
